### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by irka775** [irka775/taste_of_juices#2]
As a **software developer** I can **set up the juice blog project with all configurations and components** so that **I can ensure a good development and deployment process of this project**

**Acceptance Criteria**
- Initialize and setup a GitHub repository with a README file using CI Gitpod template.
- Install Django and start to create a new Django project.
- Add main app and a requirements.txt file for listing all project dependencies.
- Verify that the project runs without errors using Django development server.
- Add env.py file to store sensitive information.
- Add Procfile for deploy project on Heroku.
- Configure the project to use a ElephantSQL database.
- Implement image database: Cloudinary( media storage configuration) for users uploaded images.
- Update the settings.py file with the installed supportin libraries.
- Deploy project to Heroku to test deployment is successful.

**Tasks**

- [ ]  Initialize Repository and Setup CI/CD Environment

- [ ] Install and Set Up Django
- [ ] Configure Project Dependencies
- [ ] Media Storage Configuration
- [ ] Datatbase Configuration
- [ ] Update Django Settings
- [ ] Create SuperUser 
- [ ] Deploy to Heroku
