### ISSUE TITLE
Create and Setup base.html file

### ISSUE THREAD

**Issue by irka775** [irka775/taste_of_juices#3]
As a **software developer** I can **create and setup a base.html file** so that **I will have a basic structure of the page for my project to easy work in it**

**Acceptance Criteria**
- Create base.html file.
- Add navigation menu( nav bar).
- Add footer with who created and links(GitHub and LinkedIn).
- Verify and Test if is working and doesn't have bugs and if the layout is responsive and works well on different screen sizes.
- Add fixtures to project for safety purposes (Backup data base,initial setting etc.)

**Tasks**

- [ ] Create base.html file.
- [ ] Add navigation menu.
- [ ] Add footer.
- [ ] Verify and Test.
- [ ] Add Fixtures.
