### ISSUE TITLE
Create Navigation bar and Footer Content Section

### ISSUE THREAD

**Issue by irka775** [irka775/taste_of_juices#5]
As a **software developer** I can **create a navigation menu and footer content section** so that **a website user can easily navigate through the site pages. In footer content I can include who creates a website,relevant site information and who created a website.**

**Acceptance Criteria**
- For Navigation bar:
-- Create a navigation menu(Home,About,Signup,Login and Logout pages).
-- Navigation bar must be responsive on different devices.
- For Footer Content Section:
--The name of the developer are clearly visible in footer of every page.
--Relevant site information to say that website was created for "educational purposes only".
--easy to access links(LinkedIn and GitHub) and bee sure links open relevant pages in new tab.

**Tasks**

- [ ] Create the Navigation menu in base.html.
- [ ] Add links to the Navigation Bar.
- [ ] Make the Navigation Bar Responsive.
- [ ] Add developer name to Footer Section and Links.
