### ISSUE TITLE
User Registration and Authentication

### ISSUE THREAD

**Issue by irka775** [irka775/taste_of_juices#6]
As a **user** I can ** register, login, and logout** so that **I can explore the website and leave and edit comments and review**

**Acceptance Criteria**
- Implement register, login and logout functionality for users
- Verify that users can register/ login and logout of their account with an appropriate message displayed.

**Tasks**

- [ ] Install and Configure Allauth
- [ ] Implement Registration Functionality
- [ ]  Implement Login Functionality
- [ ] Implement Logout Functionality
- [ ] Verify User Authentication Functionality
