### ISSUE TITLE
 Admin Post Creation and Publishing

### ISSUE THREAD

**Issue by irka775** [irka775/taste_of_juices#7]
As a **admin** I want to be able to **create and publish posts** so that **I can** manage and share content on the website.

**Acceptance Criteria**
- Only admin can create, edit, or delete posts.
- Admin users cannot access the post creation, editing, or deletion functionalities.
- Posts should have a title,author, image and publication date.
- Admins should receive a confirmation message upon successful creation, editing, or deletion of a post.

**Tasks**

- [ ] Set Up Admin Interface
- [ ] Define Post Model
- [ ] Configure Permissions
- [ ] Create Templates and Views (Optional)
- [ ] Update Navigation
- [ ] Test and Verify Functionality
