### ISSUE TITLE
Edit post( recipe of juice)

### ISSUE THREAD

**Issue by irka775** [irka775/taste_of_juices#8]
As a **author** I can **edit the recipes that I have shared** so that **I can correct and update the recipe details if necessary.**

**Acceptance Criteria**
- Author is able to update previously created/shared recipes.
- An 'edit' button should only be visible to the author who posted the recipe.
- The author should be directed to a page containing a form with pre-populated fields.
- A confirmation message should be provided for the author after clicking the 'save' button.

**Tasks**

- [ ] Set Up Recipe Model
- [ ] Create View for Editing Recipes
- [ ] Create URL Pattern for Edit View
- [ ] Create/Edit Template
- [ ] Add 'Edit' Button
- [ ] Handle Form Submission
- [ ] Test and Verify Functionality
