### ISSUE TITLE
Create an About Page in Django

### ISSUE THREAD

**Issue by irka775** [irka775/taste_of_juices#9]
As a **user** I can **access an About page** so that **I can learn more about the website or organization**

**Acceptance Criteria**
- Create a dedicated URL for the About page
- Develop a view for the About page
- Design an HTML template for the About page
- Verify that the About page is accessible from the main navigation

**Tasks** 

- [ ] Create URL for About Page
- [ ] Develop View for About Page
- [ ] Design HTML Template for About Page
- [ ] Verify Accessibility of About Page
- [ ] Additional Task: Style the About Page (Optional)
